#!/usr/bin/env bash
# script that configures a new Ubuntu machine to Perform a 301-redirection

sudo apt-get -y update
sudo apt-get -y install nginx

echo "Hello World!" | sudo tee /var/www/html/index.html
string_replacement="server_name _;\n\trewrite ^\/redirect_me https:\/\/github.com\/Anasoud1 permanent;"
sudo sed -i "s/server_name _;/$string_replacement/" /etc/nginx/sites-enabled/default

sudo service nginx restart
